# Generated by Django 5.1.3 on 2024-12-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
